### ISSUE TITLE
After-death behavior

### ISSUE THREAD

**Issue by DavidBruant** [ecvdbdx1617/MultiSnake#116]

**Comment by Laguigue** [comment]
What is death ? Death, is a concept.. it's the unknown, the abyss, the 'néant', like the frenchs say.

Well, that is in real life. But NOT in our game ! 

**In our game, when a snake die, he's just asleep. He disappear, he's out, but he can still watch his fellow snakes still in the game fight. He only reappear when the only snake left in the arena is announced as the winner. Then, just then , every body reappear and the game restart for an other round.**

**Comment by DavidBruant** [comment]
Fixed at #124
