### ISSUE TITLE
BACK-END - Routing

### ISSUE THREAD

**Issue by clemcode** [ecvdbdx1617/MultiSnake#17]
Si on fait du SSR, besoin de gérer le routing

**Comment by DavidBruant** [comment]
Besides static assets, there is no need for routing in the usual HTTP sense. There is however a socket.io API to document:
* what are the event sent from server to clients?  which data is sent at this occasion?
* what are the event sent from clients to server? which data is sent at this occasion?

**Comment by DavidBruant** [comment]
Beginning of documentation at #96
