### ISSUE TITLE
Afficher les évènements reçus

### ISSUE THREAD

**Issue by fcoadebez** [ecvdbdx1617/MultiSnake#55]
- Connexion utilisateur
- Déconnexion
- Mouvement snake
- Collision
- Début du jeu
- Fin du jeu

**Comment by fcoadebez** [comment]
DoD : Afficher les informations voulues dans la console afin de vérifier que les fonctions marchent

**Comment by DavidBruant** [comment]
Plutôt afficher les évènements reçus

**Comment by DavidBruant** [comment]
Sort of done at #60. Events are only sent, not logged, but that's close enough
