### ISSUE TITLE
✏️ Dessiner un serpent sur l'écran

### ISSUE THREAD

**Issue by Bramvanosta** [ecvdbdx1617/MultiSnake#7]

**Comment by Bramvanosta** [comment]
**Definition of Done**
When the user opens the page, het can see an object identifiable as a snake on the screen.

**Comment by DavidBruant** [comment]
👍

**Comment by Bramvanosta** [comment]
You can close this issue, fixed by [2e5e9cb7a33fa711caac319a1bca9a3c21ef48e7]
