### ISSUE TITLE
Handle snake names server-side

### ISSUE THREAD

**Issue by DavidBruant** [ecvdbdx1617/MultiSnake#80]
Related to #14

**Comment by clemcode** [comment]
Séquence d'action : 

Client : 
- Le client se connecte.
- L'utilisateur doit rentrer son nom et valider avant de rentrer dans le jeu.

Serveur : 
- Le serveur doit récupérer et stocker le nom de l'utilisateur.
- Une fois ce nom récupéré, il doit émettre l'évènement créant le serpent.

**Comment by Clem-o2p** [comment]
Côté serveur, pour le MVP on va rester simple : 

- Le client POST un formulaire avec le nom du joueur.
- On le récupère côté serveur (avec bodyparser) et on le stocke dans un tableau, qui est renvoyé en data pour la vue.

**Comment by DavidBruant** [comment]
closed in favor of #128
