### ISSUE TITLE
Eating an Apple

### ISSUE THREAD

**Issue by rthoreau** [ecvdbdx1617/MultiSnake#9]

**Comment by rthoreau** [comment]
Critère d'acceptabilité : Quand toutes les collisions possibles sont connues, et qu'une action existe pour chacune d'entre elles.

**Comment by DavidBruant** [comment]
When can we know that the code is done?
What do we have right now? How will we know the code added moved in the right direction and there is nothing to add/remove to it as far as this issue is concerned?

**Comment by rthoreau** [comment]
What we have now : an object on the screen that can move in 4 direction to infinity.

The following collisions need to be managed : (The snake here is considered as the head of the snake)
The snake with himself [par : Controler le serpent]
The snake with the end of the map [par : Controler le serpent et Tableau de jeu]
The snake with another snake (head and body) [par : Controler le serpent et Multi user]
The snake with an object [par : Controler le serpent et Tableau de jeu]

The code is done when an action exist and work for the 4 types of collision.

**Comment by DavidBruant** [comment]
This is a bit early. Let's talk about controlling the snake as just "moving it" to begin with

**Comment by DavidBruant** [comment]
Definition of Done : 
when a snake overlaps an apple, it makes it disappear (from the board), its score increases and grows
