### ISSUE TITLE
BUG - cannot find property remove() of undefined and const BODY_PART_MARGIN

### ISSUE THREAD

**Issue by clemcode** [ecvdbdx1617/MultiSnake#97]
Reproduction : 

Après avoir rentré son pseudo, la méthode `remove()` est signalée undefined. Dès qu'une touche de déplacement est pressée, l'erreur `BODY_PART_MARGIN is not defined` survient en continue, bloquant tout déplacement du Snake.

**Comment by Fuel0** [comment]
Est ce que tu as essayé d'écrire `constante.BODY_PART_MARGIN` ?
Et as tu récupérer le fichier constant.js ?

**Comment by clemcode** [comment]
Oui le fichier est bien là, avec BODY_PART_MARGIN dedans :)

**Comment by Bramvanosta** [comment]
Fixed by #98
